// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Burtha":return img`
.bbbbbbbbbbbbbbbbbbbbbb.........
.bbbbbbbbbbbbbbbbbbbbbb.........
..fddddf.fffff..fddddf..........
...ffddffeeeeef.fddff...........
...f99dffeeeeeeffd99f...........
....f99ffdddeeeff99f............
....f99ffdddddeff99f............
....f99ffdfddfdff99f............
....f99ffddddddff99f............
....f999fdffffdf999f............
.....f999fddddf999f.............
......ffffffffffff..............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
